name: main
on:
  push:
    branches:
      - main
jobs:
  build:
    name: main
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go
      - name: checkout
        uses: actions/checkout@v2
      - name: cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: install golangci-lint
        run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.39.0
      - name: lint
        run: $(go env GOPATH)/bin/golangci-lint run --timeout=10m
      - name: test
        run: go test ./... -v -race -coverprofile=coverage.txt -covermode=atomic
      - name: Send coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.txt
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          fields: repo,commit,action,workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
