name: nightly
on:
  workflow_run:
    workflows:
      - main
    types:
      - completed
jobs:
  nightly:
    name: nightly
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go
      - name: checkout
        uses: actions/checkout@v2
      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build
        run: GOOS=linux GOARCH=amd64 go build -o reearth-backend -tags "release" "-ldflags=-X main.version=nightly -s -buildid=" -trimpath ./cmd/reearth
      - name: Package
        run: tar -zcvf reearth-backend_linux_amd64.tar.gz reearth-backend
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: reearth-backend_*.tar.gz
          artifactContentType: application/gzip
          commit: ${{ env.GITHUB_SHA }}
          name: Nightly release
          prerelease: true
          tag: nightly
          token: ${{ secrets.GITHUB_TOKEN }}
